import { GET_CHARACTERS } from '../../schema/queries';

export default {
  request: {
    query: GET_CHARACTERS,
    variables: { page: 1, name: '' },
  },
  result: {
    data: {
      characters: {
        results: [
          {
            id: '1',
            name: 'Rick Sanchez',
            image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
            species: 'Human',
            status: 'Alive',
          },
          {
            id: '2',
            name: 'Morty Smith',
            image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
            species: 'Human',
            status: 'Alive',
          },
          {
            id: '3',
            name: 'Summer Smith',
            image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
            species: 'Human',
            status: 'Alive',
          },
          {
            id: '4',
            name: 'Beth Smith',
            image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
            species: 'Human',
            status: 'Alive',
          },
          {
            id: '5',
            name: 'Jerry Smith',
            image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
            species: 'Human',
            status: 'Alive',
          },
          {
            id: '6',
            name: 'Abadango Cluster Princess',
            image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
            species: 'Alien',
            status: 'Alive',
          },
          {
            id: '7',
            name: 'Abradolf Lincler',
            image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
            species: 'Human',
            status: 'unknown',
          },
          {
            id: '8',
            name: 'Adjudicator Rick',
            image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
            species: 'Human',
            status: 'Dead',
          },
          {
            id: '9',
            name: 'Agency Director',
            image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
            species: 'Human',
            status: 'Dead',
          },
          {
            id: '10',
            name: 'Alan Rails',
            image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
            species: 'Human',
            status: 'Dead',
          },
          {
            id: '11',
            name: 'Albert Einstein',
            image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
            species: 'Human',
            status: 'Dead',
          },
          {
            id: '12',
            name: 'Alexander',
            image: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
            species: 'Human',
            status: 'Dead',
          },
          {
            id: '13',
            name: 'Alien Googah',
            image: 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
            species: 'Alien',
            status: 'unknown',
          },
          {
            id: '14',
            name: 'Alien Morty',
            image: 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
            species: 'Alien',
            status: 'unknown',
          },
          {
            id: '15',
            name: 'Alien Rick',
            image: 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
            species: 'Alien',
            status: 'unknown',
          },
          {
            id: '16',
            name: 'Amish Cyborg',
            image: 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
            species: 'Alien',
            status: 'Dead',
          },
          {
            id: '17',
            name: 'Annie',
            image: 'https://rickandmortyapi.com/api/character/avatar/17.jpeg',
            species: 'Human',
            status: 'Alive',
          },
          {
            id: '18',
            name: 'Antenna Morty',
            image: 'https://rickandmortyapi.com/api/character/avatar/18.jpeg',
            species: 'Human',
            status: 'Alive',
          },
          {
            id: '19',
            name: 'Antenna Rick',
            image: 'https://rickandmortyapi.com/api/character/avatar/19.jpeg',
            species: 'Human',
            status: 'unknown',
          },
          {
            id: '20',
            name: 'Ants in my Eyes Johnson',
            image: 'https://rickandmortyapi.com/api/character/avatar/20.jpeg',
            species: 'Human',
            status: 'unknown',
          },
        ],
        info: {
          pages: 42,
        },
      },
    },
  },
};
